apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splyce-frontend-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: splyce-frontend
    project: splyce
spec:
  project: default
  destination:
    name: in-cluster
    namespace: splyce-frontend
  source:
    path: "k8s"
    repoURL: 'git@github.com:Into-the-Fathom/splyce-frontend-app.git'
    targetRevision: ci-cd
    helm:
      valueFiles:
        - values-dev.yaml
      parameters:
        - name: image.tag
          value: latest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
